=== polvallsortiz/PTILabs/Lab2/CarRental.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="carrental">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="rental" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="make"/>
              <xs:element type="xs:string" name="model"/>
              <xs:element type="xs:byte" name="nofdays"/>
              <xs:element type="xs:byte" name="nofunits"/>
              <xs:element type="xs:byte" name="discount"/>
            </xs:sequence>
            <xs:attribute type="xs:short" name="id" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== polvallsortiz/PTILabs/Lab2/CarRental.xml
<?xml version="1.0" encoding="UTF-8"?>
<carrental xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CarRental.xsd"><rental id="1234"><make>Seat</make><mo>Ibiza</mo><nofdays>2</nofdays><nofunits>3</nofunits><discount>14</discount></rental><rental id="1234"><make>Volvo</make><model>V40</model><nofdays>10</nofdays><nofunits>1</nofunits><discount>10</discount></rental></carrental>
